spring:
  application:
    name: ark
  profiles:
    active: dev
  session:
    store-type: none

  http:
     encoding:
         charset: UTF-8
         force: true
         enabled: true
     multipart:
         enabled: true
         max-file-size: 200MB
         max-request-size: 200MB

  aop:
    proxy-target-class: true
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    settings:
      template_update_delay: 0
      classic_compatible: true
      number_format: 0.######
      template_exception_handler: ignore
    request-context-attribute: rc
    charset: UTF-8

  redis:
    database: 0
    host: 58.87.111.18
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 18
      min-idle: 0
    timeout: 0


sitemesh:
  contentPath: /*
  decoratorPath: classpath:/layouts/default.ftl
  excludedPaths: /js/*,/assets/*,/css/*



management:
  security:
    enabled: false


logging.level.project.user.UserClient: DEBUG

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.siro.ark.entity

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.siro.ark.entity
  global-config:
    id-type: 2
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
    metaObjectHandler: com.siro.ark.web.config.plus.SysMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

security:
  basic:
    enabled: false

